### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by smfilipe** [tpcstld/2048#11]
The 2048 icon has disappeared. Now it only shows a generic Android Icon.

**Comment by tpcstld** [comment]
Thanks for the bug report. I think I've isolated the issue and I'll be deploying a fix soon.

**Comment by tpcstld** [comment]
Hey I deployed a potential fix. Everyone should be getting the update within 24 hours. Let me know if this issue still persists after you've updated again. :)

**Comment by smfilipe** [comment]
I've updated to the last version and the bug is fixed. Thanks for the quick fix.
