### ISSUE TITLE
annoying 'install google play' message

### ISSUE THREAD

**Issue by lvmm** [tpcstld/2048#15]
Version 1.3.0 added google play cloud save feature. Presumably because of this when google play is disabled an annoying message requesting that google play should be installed pops up every time 2048 is started, the game itself works fine after installation is cancelled. Please disable this message.

**Comment by tpcstld** [comment]
@lvmm I did a bit of work a few months ago to fix this issue, does this problem still occur everytime the app is started?

**Comment by lvmm** [comment]
No, it is gone. Thanks!

**Comment by plonibarploni** [comment]
I still see this message on my phone which doesn't have Google Play Services installed. When I click OK to close the dialog the game plays fine.

The exact message is:
> 2048 won't run without Google Play services, which are not supported by your device.

**Comment by tpcstld** [comment]
Did it disappear for a while? And come back? :/

If it's annoying you can try to install an older release and it'll probably stop it afterwards. It's kinda hard to get a phone without Google play services

**Comment by plonibarploni** [comment]
> Did it disappear for a while? And come back? :/

I don't know. I just installed the app from Github Releases and I keep on seeing it.

> It's kinda hard to get a phone without Google play services

If I'm not mistaken, it should be possible to set up such a virtual device relatively easily with the emulator included in Android Studio.

**Comment by plonibarploni** [comment]
I loaded the app in an Android virtual machine which (supposedly) doesn't have Google Play Services, and I didn't see the message or a login prompt.

However, while reviewing the code I noticed that the login prompt is only disabled in the last case, but not the first ones. Perhaps disabling it in those cases would help?
https://github.com/tpcstld/2048/blob/aa89b829c3f4e193c69a678b9e186cdb4ffd3012/2048/base/src/main/java/com/tpcstld/twozerogame/MainActivity.java#L203-L217
